# Generated by Django 5.1.3 on 2024-11-21 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_bordado_delete_seumodelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('numero_interno', models.CharField(max_length=20, unique=True, verbose_name='Número Interno')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atendente', models.CharField(max_length=100, verbose_name='Nome do Atendente')),
                ('texto_bordado', models.TextField(verbose_name='Texto a ser Bordado')),
                ('cor_bordado', models.CharField(max_length=50, verbose_name='Cor do Bordado')),
                ('tipo_fonte', models.CharField(max_length=50, verbose_name='Tipo de Fonte')),
                ('data_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.DeleteModel(
            name='Bordado',
        ),
    ]
